server:
  port: 8090
service:
  version: 1.0.0

dubbo:
  cloud:
    # The subscribed services in consumer side
    subscribed-services: b0x0-cloud-provider1,b0x0-cloud-provider2
  protocols:
    dubbo:
      # dubbo 协议
      name: dubbo
      # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
      port: -1
  consumer:
    check: false
    timeout: 30000
    filter: paramPassFilter



